### ISSUE TITLE
Removed symbols without SONAME increment

### ISSUE THREAD

**Issue by tiger-jmw** [ClusterLabs/libqb#134]
Hi,

Somewhere between libqb 0.11 and 0.17 exported symbols were added and dropped, but the SONAME was not incremented. This makes it difficult to automatically establish dependencies for software making use of the library.

The libtool manual has this to say about the matter:
"*Never try to set the interface numbers so that they correspond to the release number of your package. This is an abuse that only fosters misunderstanding of the purpose of library versions.*"

lib/Makefile.ac currently uses -version-number to specify 0.17.1 as the soversion. It should use -version-info and the current SONAME 0 should be incremented to reflect the interface changes. Please see https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

Could you set the SONAME correctly? Or, if that can't be done right now, at least agree to what the SONAME for 0.17.0 should be (I suggest 1:0:0) so I can use that in the Debian package, where we have a time-critical problem. (There seem to be no interface changes between 0.17.0 and 0.17.1.)

Thanks!

**Comment by rikkotec** [comment]
Interesting, I'm not getting any of those dropped symbols reported in the diff in my package, perhaps you forgot to generate the symbols file for .0.11 version prior to comparing them to 0.17.1? 

There was no symbols file for 0.11 or 0.17.0, they needed to be generated (in order) prior to checking the diff against 0.17.1

@tiger-jmw  would you mind revewing this for me:

https://mentors.debian.net/package/libqb

**Comment by rikkotec** [comment]
@davidvossel 

The time critical issue was that the freeze on Jessie was imminent. The Pacemaker stack is not going to be in Jessie's release because the packages were not updated for Debian in time. The freeze is already in place.

It's too late now to resolve that, but we're working on getting the packages up-to-date so they can be added to the repositories once Jessie is officially released.

I've not heard back from @tiger-jmw so I'm not sure if I'm just not seeing what he is talking about, but I'm rather certain that the issue we're having is due to the fact that there *hasn't* been a symbols file in any of our packages for the Pacemaker cluster stack (which I've resolved for libqb, and which others are paying attention to now for the other packages in the stack).

The current libqb package that I'm maintaining is seemingly fine, other issues occur because of issues with other packages (older versions of software, missing symbol files in cross-dependent library packages, etc). Building everything from source works just fine - which suggests to me that the issue is with the Debian packages specifically.

All-in-all the entire stack needs to be brought up to date on Debian, which is not your problem - but ours :)

Hope that helps to clarify for you.

**Comment by davidvossel** [comment]
@rikkotec excellent, glad to hear it's all sorted out. It's unfortunate pacemaker missed the release though.

**Comment by wferi** [comment]
Sorry, but I get results like @tiger-jmw. For example, `qb_ipc_us_recv_ready` is present in 0.13.0 but missing from 0.14.0. More precisely:

symbol|removal
---:|---
`qb_ipc_us_recv_ready`|73731f0643aae9afc37e54d350a7af017030b6ce
`qb_ipcc_pmq_connect` `qb_ipcc_smq_connect` `qb_ipcs_pmq_init` `qb_ipcs_smq_init` |70a9623a48a7cc30ec079aa2762a35a4b7fc7add
`qb_ipcs_dispatch_service_request`|70a7aca77f663328c5701b21024e0090a0d267d9
`qb_vsprintf_serialize`|a55554efb1e355948aa86cacfe91d15b0a809f5e

These warrant a new SONAME, I think. What about papering over the pre-0.17 changes by giving 0.17.0 and 0.17.1 (in principle) [`-version-info 1:0:0`](http://www.gnu.org/software/libtool/manual/html_node/Link-mode.html) as @tiger-jmw recommended, and continuing from there?

**Comment by rikkotec** [comment]
@davidvossel 

Yes, very sorry - When we added complete symbols references from snapshot.debian.org we included the 0.13 and 0.14 symbols (which I did not do correctly when I only refrenced 0.11 and 0.17.0 previously.)

**Comment by wferi** [comment]
@davidvossel, what's your word on this issue? Even if you don't take immediate action, knowing your intentions would help us produce more future proof packages and maybe even create applicable pull requests to resolve this issue.

**Comment by davidvossel** [comment]
@wferi I took over maintenance of libqb around version 0.14.4. Since then I've been careful to adhere to standard practices involving not modifying/deleting the public API without incrementing the soname. It was a mistake for libqb to go down the path of using -version-number instead of -version-info. I don't know all the historical reasons for that, but I plan to continue to use -version-number for the time being. If we encounter a situation where the soname needs to change, I will evaluate switching to -version-info for all releases after that point. I don't anticipate making any API changes that require a soname change for quite some time though.

I can provide a bit of historical context to why symbols may have changed without a new soname. I know at one point before I took over the project, libqb was only consumed by pacemaker and corosync. It is possible that the soname wasn't incremented when it technically should have been because all the players involved with libqb were aware of the changes. If that happened, understand that I have no plans of continuing that behavior in the future. Any modification/deletion of the API will result in a new soname.

**Comment by tiger-jmw** [comment]
I think http://upstream-tracker.org/versions/libqb.html probably provides an easier view of what's going on than my diffs. Between 0.16.0 and 0.17.0 in qblog.h the qb_log_filter_type enum gained new values at the low end, changing the values of existing members. In 0.17.1 they seem to have been corrected.

Therefore this isn't symbol removal as I originally though (sorry for any confusion) but it *does* make breaking changes, so perhaps there should have been two bumps by now.

Does that make more sense?

**Comment by davidvossel** [comment]
@tiger-jmw yes it makes sense. However, I'm not bumping soname for that.

The enum change you are referring to in 0.17.0 has no negative effect. Even though I accidentally added values at the beginning on an public enum instead of the end, it actually doesn't matter. The first 3 and last 3 values in that enum are functionally equivalent for anyone who built using 0.16.0 and upgraded to 0.17.0.  No one's previous deployments break by updating. Between 0.17.0 and 0.17.1, if some one took advantage of the new regex features (which i'm nearly 100% certain no one did) then if they updated form 0.17.0 to 0.17.1, their regex filters would not work.

**Comment by kgaillot** [comment]
libqb switched from -version-number to -version-info with the 0.17.2 release. In that release, the soname version was changed from 0:17:1 to 17:2:17, which may look odd but is the -version-info equivalent of the -version-number.

The soname versioning should be correct going forward, but we're not going to bump the version to account for past changes.

Also, there is an ABI compatibility report since the most recent release available at http://clusterlabs.github.io/libqb/ (currently "0.17.2_to_1.0rc1").
