### ISSUE TITLE
Drop maint-0.5 branch

### ISSUE THREAD

**Issue by jonesmz** [ClusterLabs/libqb#227]
The branch is 5 years old, and has only 4 commits in it. Is there value in keeping it?

**Comment by chrissie-c** [comment]
I don't really see the point of deleting a branch even though it's dead. They don't take up significant space or distract IMHO. There are several other branches present (and TBH I don't even know what they're for) and I'm happy to leave them as a record of the development work that went on at the time.

**Comment by jonesmz** [comment]
I opened the ticket because I spent 15 minutes looking at the maint-0.5 branch before realizing that it was so old. So in my opinion it's a distraction to potential contributors.

Either way, it's your project, feel free to close this issue if you want.

**Comment by jnpkrn** [comment]
Also note that tag `v0.6.0` is *not* present at `master` branch.
If we don't want to lose bits from historical development, it would not be wise to drop that branch.

@jonesmz, as a GitHub user, you should consider checking `/branches` URL ([for libqb](https://github.com/ClusterLabs/libqb/branches)) as it indicates which branches are active clearly. Also since GIt 2.7.0, you can use `git branch --sort=-committerdate` to get the same picture.

**Comment by jnpkrn** [comment]
So, can this be closed with "status quo doesn't get anyone too annoyed if discretion is used"?
